package eu.opentxs.bridge;


public enum Text {
	CONSOLE_TITLE,
	WELCOME_HEADER,

	FEATURE_UNSUPPORTED_YET,
	FEATURE_DISABLED_SERVER_BUG,
	NAME_UNKNOWN,

	COMMAND_UNKNOWN,
	COMMAND_ABORTED,
	COMMAND_ENDED_WITH_SUCCESS,

	EMPTY_ARGUMENT_ERROR,
	
	VALIDATION_MUST_BE_BOOLEAN,
	VALIDATION_MUST_BE_DATE,
	VALIDATION_MUST_BE_DATE_FUTURE,
	VALIDATION_MUST_BE_NUMBER,
	VALIDATION_MUST_BE_NUMBER_RANGE,
	VALIDATION_MUST_BE_INTEGER,
	VALIDATION_MUST_BE_INTEGER_RANGE,
	VALIDATION_MUST_BE_ID,
	VALIDATION_MUST_BE_INTEGER_OR_ID,
	VALIDATION_MUST_BE_INTEGER_LIST,
	VALIDATION_MUST_BE_INTEGER_LIST_RANGE,

	INTEGER_EXPECTED_ERROR,
	INTEGER_LIST_EXPECTED_ERROR,
	FLOAT_EXPECTED_ERROR,
	DOUBLE_EXPECTED_ERROR,
	DATE_EXPECTED_ERROR,
	
	NYM_NEEEDS_TO_REGISTERED_ERROR,

	INTEGER_LIST_SEPARATOR,

	SERVER_ID,
	NYM_ID,
	ASSET_ID,
	ACCOUNT_ID,

	FOLDER_SERVERS,
	FOLDER_NYMS,
	FOLDER_ASSETS,
	FOLDER_CHEQUES,
	FOLDER_CASH,

	OPEN_FILE_TITLE,
	OPEN_FILE,
	SAVE_FILE_TITLE,
	SAVE_FILE,
	FILE_DOES_NOT_EXIST_TITLE,
	FILE_DOES_NOT_EXIST,
	FILE_OVERWRITE_TITLE,
	FILE_OVERWRITE,
	FILE_SAVED_AS,

	ISSUER_SIGN,

	BANK,
	SERVER,
	NAME,

	MY_NYM,
	MY_ASSET,
	MY_ACCOUNT,

	INFO,
	LOG,
	WARN,
	SKIP,
	SUCCESS,
	
	;
	@Override
	public String toString() {
		return Localizer.get().getString(name());
	}
}
