-----BEGIN OT ARMORED MESSAGE-----
Version: Open Transactions 0.89.q
Comment: http://github.com/FellowTraveler/Open-Transactions/wiki

eJx1kE9zokAQxU97mU8x5dWKoEQM1poUCAGkGFBAw95QR0D5OwMonvPBFzW1yWX7
Nv3mve7+gc9fT7eSFFVH0NFVpMjQVBxHVJW7ALSARlPoiKYPwO+3S5rABhMa59ms
NxywvbfXrm25KaY0CDH4FkedCOA+qLAThxned9+5l+Ezx40FoXczhbha4bLGtAIw
a1NdnvVkX5F4b7LfFdvzXiWHys5ogozrhJfkWnLfxWMshkYQ+6Osy6aYdNNuPjI8
eLl2XlibeW1wG0kUW+eYGn5JVV4dub5+2Zc+76O6VjsfeUxFddrtdF+F+d7l/vx3
zyv4QecLy52S6HqrL0Drx8VTaBU4gy4JMhrsqq5DITt4EQYlmOdpirNqCqOqKqYM
E8ZVVG8Huzxl3nGS5OfO1OAEE+YW8fQzgjnHpxiYuAqmsCtRdgXQ5YnShm1NG010
5WDRTd9q+G0aUaJgxbtOItZe68N43Rwa2/NHrK72y0XfXO9Qa6glysGCa/u2fVpE
V9ZbYLewWTvaeauxybhcPnJ8fakz5E+SIjImBfOMzvo4SShfaMawRB+hAPjaHR+D
RrDFYjNR3YOs4hNN+flSK7ToophKvloiy3uXtA+/FU+zB0YFyf+B+BfPK8eG
-----END OT ARMORED MESSAGE-----

